<?php
/**
 * Class GrepServiceTest
 *
 * @author Mauro Moreno <moreno.mauro.emanuel@gmail.com>
 */
namespace MauroMoreno\GrepBundle\Tests\GrepServices;

use MauroMoreno\GrepBundle\Tests\Fixtures\app\AppKernel;
use MauroMoreno\GrepBundle\Services\GrepDirectoryService;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Class GrepServiceTest
 * @package MauroMoreno\GrepBundle\Tests\GrepService
 */
class GrepServiceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ContainerInterface
     */
    private $container;

    /**
     * {@inheritdoc}
     */
    protected function setUp()
    {
        $kernel = new AppKernel(getenv('ENV'), getenv('DEBUG') === 'true');
        $kernel->boot();

        $this->container = $kernel->getContainer();
        mkdir(__DIR__ . '/empty_directory');
    }

    /**
     * {@inheritdoc}
     */
    protected function tearDown()
    {
        rmdir(__DIR__ . '/empty_directory');
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    /**
     * Test if service is defined in container.
     */
    public function testServiceIsDefinedInContainer()
    {
        $service = $this->container->get(
            'mauro_moreno_grep.grep_directory_service'
        );

        $this->assertInstanceOf(GrepDirectoryService::class, $service);
    }

    /**
     * Test find empty pattern
     */
    public function testFindEmptyPattern()
    {
        $this->setExpectedException(
            'InvalidArgumentException',
            'Pattern cannot be empty.'
        );
        $this->getGrepDirectoryService()->find('', __DIR__ . '/directory');
    }

    /**
     * Test find empty directory
     */
    public function testFindEmptyDir()
    {
        $this->setExpectedException(
            'InvalidArgumentException',
            'The target directory cannot be empty.'
        );
        $this->getGrepDirectoryService()->find('pattern', '');
    }

    /**
     * Test find wrong directory
     */
    public function testFindWrongDirectory()
    {
        $this->setExpectedException(
            'InvalidArgumentException',
            'The target directory "not_directory" does not exist.'
        );
        $this->getGrepDirectoryService()->find('pattern', 'not_directory');
    }

    /**
     * Test find empty directory
     */
    public function testFindEmptyDirectory()
    {
        $grep_directory_service = $this->getGrepDirectoryService();
        $found = $grep_directory_service->find(
            'pattern',
            __DIR__ . '/empty_directory'
        );

        $this->assertEquals('/pattern/', $grep_directory_service->getPattern());
        $this->assertEquals(
            __DIR__ . '/empty_directory',
            $grep_directory_service->getDirectory()
        );

        $file_iterator = $grep_directory_service->getFileIterator();
        $this->assertInstanceOf(
            \GlobIterator::class,
            $file_iterator
        );

        // TODO: Fix when bug is fixed https://bugs.php.net/bug.php?id=55701
        // $this->assertEquals(0, $file_iterator->count());
        $this->assertEquals(0, count(iterator_to_array($file_iterator)));

        $this->assertFalse($found);
    }

    /**
     * Test find empty result
     */
    public function testFindEmptyResult()
    {
        $grep_directory_service = $this->getGrepDirectoryService();
        $found = $grep_directory_service->find(
            'bad',
            __DIR__ . '/directory'
        );

        $file_iterator = $grep_directory_service->getFileIterator();
        $this->assertInstanceOf(
            \GlobIterator::class,
            $file_iterator
        );

        // TODO: Fix when bug is fixed https://bugs.php.net/bug.php?id=55701
        // $this->assertEquals(0, $file_iterator->count());
        $this->assertEquals(4, count(iterator_to_array($file_iterator)));
        $this->assertEquals(0, count($found));
    }

    /**
     * Test find result
     */
    public function testFindResult()
    {
        $grep_directory_service = $this->getGrepDirectoryService();
        $found = $grep_directory_service->find(
            'pattern',
            __DIR__ . '/directory'
        );

        $file_iterator = $grep_directory_service->getFileIterator();
        $this->assertInstanceOf(
            \GlobIterator::class,
            $file_iterator
        );

        // TODO: Fix when bug is fixed https://bugs.php.net/bug.php?id=55701
        // $this->assertEquals(0, $file_iterator->count());
        $this->assertEquals(4, count(iterator_to_array($file_iterator)));
        $this->assertEquals(2, count($found));
        $this->assertEquals('file_1', $found[0]['filename']);
        $this->assertEquals(
            __DIR__ . '/directory/file_1',
            $found[0]['pathname']
        );
    }

    /**
     * Test find empty result, extension set
     */
    public function testFindEmptyResultExtensionSet()
    {
        $grep_directory_service = $this->getGrepDirectoryService();
        $found = $grep_directory_service->find(
            'bad',
            __DIR__ . '/directory',
            'txt'
        );

        $file_iterator = $grep_directory_service->getFileIterator();
        $this->assertInstanceOf(
            \GlobIterator::class,
            $file_iterator
        );

        // TODO: Fix when bug is fixed https://bugs.php.net/bug.php?id=55701
        // $this->assertEquals(0, $file_iterator->count());
        $this->assertEquals(2, count(iterator_to_array($file_iterator)));
        $this->assertEquals(0, count($found));
    }

    /**
     * Test find result, extension set
     */
    public function testFindResultExtensionSet()
    {
        $grep_directory_service = $this->getGrepDirectoryService();
        $found = $grep_directory_service->find(
            'pattern',
            __DIR__ . '/directory',
            'txt'
        );

        $file_iterator = $grep_directory_service->getFileIterator();
        $this->assertInstanceOf(
            \GlobIterator::class,
            $file_iterator
        );

        // TODO: Fix when bug is fixed https://bugs.php.net/bug.php?id=55701
        // $this->assertEquals(0, $file_iterator->count());
        $this->assertEquals(2, count(iterator_to_array($file_iterator)));
        $this->assertEquals(1, count($found));
        $this->assertEquals('file_3.txt', $found[0]['filename']);
        $this->assertEquals(
            __DIR__ . '/directory/file_3.txt',
            $found[0]['pathname']
        );
    }

    /**
     * Get GrepDirectoryService instance
     * @return GrepDirectoryService
     */
    private function getGrepDirectoryService()
    {
        return new GrepDirectoryService();
    }

}
