parameters:
  mauro_moreno_find.find_directory_service.class: "MauroMoreno\\FindBundle\\Service\\FindDirectoryService"
  mauro_moreno_find.finder.class: "MauroMoreno\\FindBundle\\Service\\Finder"
  mauro_moreno_find.lister.class: "MauroMoreno\\FindBundle\\Service\\Lister"

services:
  mauro_moreno_find.finder:
    class: %mauro_moreno_find.finder.class%

  mauro_moreno_find.lister:
    class: %mauro_moreno_find.lister.class%

  mauro_moreno_find.find_directory_service:
    class: %mauro_moreno_find.find_directory_service.class%
    arguments:
      - mauro_moreno_find.finder
      - mauro_moreno_find.lister